{100}{}{Before you a much older gentleman resembling a cowboy leans against the side of the department store}
{101}{}{The old man cowboy seeking the Big Chungus}
{102}{}{his hat tips downwards covering his expression of melancholy. A strong smell of whiskey eminates from his presence.}
{103}{}{Howdy stranger!, have you ever heard of Big Chungus before?}
{104}{}{Big Chungus?}
{105}{}{I'm aware of Big Chungus}
